from pydantic import BaseModel, EmailStr
from pydantic import Field
from task_model import  StatusEnum ,priorityEnum
from typing import  Optional
from datetime import datetime
class UserCreate(BaseModel):
    username: str
    email: EmailStr
    password: str = Field(..., max_length=72)

class UserLogin(BaseModel):
    email: EmailStr
    password: str

class UserResponse(BaseModel):
    id: int
    username: str
    email: EmailStr

# --------------------------
# Pydantic Schema
# --------------------------
class TaskSchema(BaseModel):
    id: int = None  # will be auto-generated by DB
    title: str
    description: Optional[str] = None
    status: StatusEnum = StatusEnum.pending
    priority: priorityEnum = priorityEnum.medium
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        orm_mode = True


